### ISSUE TITLE
Timestamp support?

### ISSUE THREAD

**Issue by canselcik** [nokia/nperf#1]
First of all, amazing work. I just had a chance to test it and works wonderfully and addresses an important use case for me.

While the collated output works great with `flamegraph.pl`, I was also hoping to be able to use it with https://github.com/Netflix/flamescope.

Flamescope seems to be unable to parse the timestamps to divide the perf output to discrete time intervals. Is is because this is missing in the output unlike the normal `perf` output would?

Thanks.

**Comment by koute** [comment]
`nperf collate` by default outputs already preprocessed traces which FlameScope cannot load AFAIK.

I've just added raw perf-like output to the `collate` subcommand, so it should work with FlameScope now. Try running `nperf collate --format=perf-like datafile > traces` and then load that into the FlameScope.

**Comment by canselcik** [comment]
Hi,

Thanks for addressing this so quickly. I will try the commit https://github.com/nokia/nperf/commit/5b00d8d2751dc0b9e772b2cff272351e642a463e and close the issue if it works.
