### ISSUE TITLE
Building fails with SIGSEV

### ISSUE THREAD

**Issue by tumdum** [nokia/nperf#15]
Executing [repro.sh.txt](https://github.com/koute/not-perf/files/4096426/repro.sh.txt) produces compilation failure with sigsev, logs: [log.txt](https://github.com/koute/not-perf/files/4096469/log.txt)

**Comment by koute** [comment]
Hmm... this is very interesting!

According to those logs it crashes in [`libc` crate's `build.rs`](https://github.com/rust-lang/libc/blob/master/build.rs), which is very very strange as that script doesn't have any `unsafe` nor any external dependencies. And of course I can't reproduce it on my system. ):

1. Is it always reproducible on your system?
2. Do you have any `$RUSTFLAGS` set? (Or flags in `.cargo/config`.)
3. Does it also crash if you manually run `/home/klak/tmp/not-perf/target/release/build/libc-80018afddfa52891/build-script-build` after running `cargo build --release`?
4. Does it also crash if you clone `libc` and try to build it by itself?

**Comment by tumdum** [comment]
1. Yes
2. `$RUSTFLAGS` are empty and I don't have `~/.cargo/config`
3. Yes
4. Yes :(

**Comment by koute** [comment]
That is really interesting. I guess at this point it would be interesting to see where exactly it SIGSEGVs - maybe then we can figure out why it does it.

Can you try running the build script under `gdb`? IIRC the build scripts might be built by-default in release mode (I'm not sure), so it may be necessary to `cargo new --bin` a new crate, copy the `build.rs` into its `src/main.rs` and perhaps run it with the same environment variables as the original `build.rs` to properly be able to debug it.

**Comment by bjorn3** [comment]
> the build scripts might be built by-default in release mode

I believe they are build with the same codegen options as the rest of the rlibs/executables by default.

**Comment by tumdum** [comment]
Closing - I no longer have access to that machine and I was never able to reproduce this on other machines.
