### ISSUE TITLE
Missing Cargo.lock

### ISSUE THREAD

**Issue by DarrenTsung** [nokia/nperf#4]
Hi, 

Thanks for the useful tool! I had trouble building this project though, because the Cargo.lock file is missing and so defaulted to using `gimli 0.16.1` for some of the dependencies. This caused the replace to not work correctly.

Thanks!

**Comment by koute** [comment]
Thanks for the report!

I switched back to `gimli` from `crates.io` and I've added `Cargo.lock` to avoid such situations in the future.
